---
- name: Create directory /srv/www
  file:
    path: /srv/www
    state: directory
    owner: www-data
    group: www-data
    recurse: yes

- name: Download and extract WordPress
  shell: "/usr/bin/curl https://wordpress.org/latest.tar.gz | /usr/bin/sudo -u www-data /usr/bin/tar zx -C /srv/www"

# - name: Download WordPress
#   get_url:
#     url: https://wordpress.org/latest.zip
#     dest: /home/vagrant/wordpress.zip
#     checksum: "sha1:{{wp_checksum.content}}"

- name: Enable WordPress site
  command: "/usr/sbin/a2ensite wordpress"

- name: Enable URL rewriting
  command: "/usr/sbin/a2enmod rewrite"

- name: Disable default site
  command: "/usr/sbin/a2dissite 000-default"

- name: Reload Apache
  shell: "/usr/sbin/apachectl configtest && /usr/sbin/service apache2 reload"

- name: Copy wp-config.php
  template:
    src: wp-config.php.j2
    dest: /srv/www/wordpress/wp-config.php
    owner: www-data
    group: www-data
    mode: '0644'

- name: Install WP-CLI
  shell: "/usr/bin/curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && /usr/bin/sudo /usr/bin/mv wp-cli.phar /usr/local/bin/wp && /usr/bin/chmod +x /usr/local/bin/wp"

- name: Install WordPress
  shell: "/usr/local/bin/wp core install --allow-root --path=/srv/www/wordpress --url=http://192.168.33.10 --title='BlogEjemplo' --admin_user=admin --admin_password=adminpass --admin_email=correo@example.com"

- name: Create Page
  shell: "/usr/local/bin/wp post create --allow-root --path=/srv/www/wordpress --post_type=page --post_title='Hola, soy Juan Luis Borrego Herrera!' --post_content='Este es un post de ejemplo' --post_status=publish | /usr/bin/grep -Eo '[0-9]{1,4}' > /tmp/id_page.txt"

- name: Update Show on Front
  shell: "/usr/local/bin/wp option update --allow-root --path=/srv/www/wordpress show_on_front 'page'"

- name: Update Page on Front
  shell: "/usr/local/bin/wp option update --allow-root --path=/srv/www/wordpress page_on_front \"$(/usr/bin/cat /tmp/id_page.txt)\""
