Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end


    config.vm.provision :ansible_local do |ansible|
       ansible.playbook       = "ansible/playbook.yml"
       ansible.verbose        = true
       ansible.install        = true
      #  ansible.limit          = "all" # or only "nodes" group, etc.
      #  ansible.inventory_path = "inventory"
    end
end
